// Code generated by mockery v2.39.1. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository_mock is an autogenerated mock type for the UserRepository type
type UserRepository_mock struct {
	mock.Mock
}

type UserRepository_mock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository_mock) EXPECT() *UserRepository_mock_Expecter {
	return &UserRepository_mock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: _a0, _a1
func (_m *UserRepository_mock) Add(_a0 context.Context, _a1 User) (*User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, User) (*User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, User) *User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, User) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_mock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type UserRepository_mock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 User
func (_e *UserRepository_mock_Expecter) Add(_a0 interface{}, _a1 interface{}) *UserRepository_mock_Add_Call {
	return &UserRepository_mock_Add_Call{Call: _e.mock.On("Add", _a0, _a1)}
}

func (_c *UserRepository_mock_Add_Call) Run(run func(_a0 context.Context, _a1 User)) *UserRepository_mock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(User))
	})
	return _c
}

func (_c *UserRepository_mock_Add_Call) Return(_a0 *User, _a1 error) *UserRepository_mock_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_mock_Add_Call) RunAndReturn(run func(context.Context, User) (*User, error)) *UserRepository_mock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddOrUpdate provides a mock function with given fields: _a0, _a1
func (_m *UserRepository_mock) AddOrUpdate(_a0 context.Context, _a1 User) (*User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddOrUpdate")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, User) (*User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, User) *User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, User) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_mock_AddOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrUpdate'
type UserRepository_mock_AddOrUpdate_Call struct {
	*mock.Call
}

// AddOrUpdate is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 User
func (_e *UserRepository_mock_Expecter) AddOrUpdate(_a0 interface{}, _a1 interface{}) *UserRepository_mock_AddOrUpdate_Call {
	return &UserRepository_mock_AddOrUpdate_Call{Call: _e.mock.On("AddOrUpdate", _a0, _a1)}
}

func (_c *UserRepository_mock_AddOrUpdate_Call) Run(run func(_a0 context.Context, _a1 User)) *UserRepository_mock_AddOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(User))
	})
	return _c
}

func (_c *UserRepository_mock_AddOrUpdate_Call) Return(_a0 *User, _a1 error) *UserRepository_mock_AddOrUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_mock_AddOrUpdate_Call) RunAndReturn(run func(context.Context, User) (*User, error)) *UserRepository_mock_AddOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: _a0, _a1
func (_m *UserRepository_mock) Query(_a0 context.Context, _a1 Specification) ([]User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Specification) ([]User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Specification) []User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, Specification) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_mock_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type UserRepository_mock_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 Specification
func (_e *UserRepository_mock_Expecter) Query(_a0 interface{}, _a1 interface{}) *UserRepository_mock_Query_Call {
	return &UserRepository_mock_Query_Call{Call: _e.mock.On("Query", _a0, _a1)}
}

func (_c *UserRepository_mock_Query_Call) Run(run func(_a0 context.Context, _a1 Specification)) *UserRepository_mock_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Specification))
	})
	return _c
}

func (_c *UserRepository_mock_Query_Call) Return(_a0 []User, _a1 error) *UserRepository_mock_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_mock_Query_Call) RunAndReturn(run func(context.Context, Specification) ([]User, error)) *UserRepository_mock_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: _a0, _a1
func (_m *UserRepository_mock) Remove(_a0 context.Context, _a1 User) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, User) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_mock_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type UserRepository_mock_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 User
func (_e *UserRepository_mock_Expecter) Remove(_a0 interface{}, _a1 interface{}) *UserRepository_mock_Remove_Call {
	return &UserRepository_mock_Remove_Call{Call: _e.mock.On("Remove", _a0, _a1)}
}

func (_c *UserRepository_mock_Remove_Call) Run(run func(_a0 context.Context, _a1 User)) *UserRepository_mock_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(User))
	})
	return _c
}

func (_c *UserRepository_mock_Remove_Call) Return(_a0 error) *UserRepository_mock_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_mock_Remove_Call) RunAndReturn(run func(context.Context, User) error) *UserRepository_mock_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *UserRepository_mock) Update(_a0 context.Context, _a1 User) (*User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, User) (*User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, User) *User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, User) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_mock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepository_mock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 User
func (_e *UserRepository_mock_Expecter) Update(_a0 interface{}, _a1 interface{}) *UserRepository_mock_Update_Call {
	return &UserRepository_mock_Update_Call{Call: _e.mock.On("Update", _a0, _a1)}
}

func (_c *UserRepository_mock_Update_Call) Run(run func(_a0 context.Context, _a1 User)) *UserRepository_mock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(User))
	})
	return _c
}

func (_c *UserRepository_mock_Update_Call) Return(_a0 *User, _a1 error) *UserRepository_mock_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_mock_Update_Call) RunAndReturn(run func(context.Context, User) (*User, error)) *UserRepository_mock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository_mock creates a new instance of UserRepository_mock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository_mock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository_mock {
	mock := &UserRepository_mock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
