with-expecter: true
inpackage: true
mockname: "{{.InterfaceName}}_mock"
recursive: true
packages:
  github.com/AndreyAD1/helsinki-guide/internal/infrastructure/repositories:
    interfaces:
      BuildingRepository:
      NeighbourhoodRepository:
      ActorRepository:
