with-expecter: true
inpackage: true
mockname: "{{.InterfaceName}}_mock"
recursive: true
packages:
  github.com/AndreyAD1/helsinki-guide/internal/bot/infrastructure/repositories:
    interfaces:
      BuildingRepository:
      NeighbourhoodRepository:
      ActorRepository:
      SettingRepository:
  github.com/AndreyAD1/helsinki-guide/internal/bot/handlers:
    interfaces:
      InternalBot:
  github.com/AndreyAD1/helsinki-guide/internal/bot/services:
    interfaces:
      Buildings:
      Settings:
