name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      RUN_COMMAND: ${{ secrets.ROOT_PATH}}${{ vars.SCRIPT_PATH}} '${{ secrets.DATABASE_URL}}' '${{ secrets.BOT_TOKEN}}' '${{ github.sha}}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build an image
        run: docker build --tag andreyad/helsinki-guide:${{ github.sha }} .

      - name: Push an image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/helsinki-guide:${{ github.sha }}

      - name: Add an SSH key
        run: touch ~/env_key && echo '${{ secrets.KEY}}' > ~/env_key && chmod 600 ~/env_key
      
      - name: Copy a startup script
        run: scp -o StrictHostKeyChecking=no -i ~/env_key ./deployments${{ vars.SCRIPT_PATH}} ${{ secrets.USER}}@${{ secrets.HOST}}:${{ secrets.ROOT_PATH}}

      - name: Run the service
        run: ssh -o StrictHostKeyChecking=no -i ~/env_key ${{ secrets.USER}}@${{ secrets.HOST}} "source $RUN_COMMAND"