name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build an image
        run: make build

      - name: Push an image
        run: docker push andreyad/helsinki-guide

      - name: Add an SSH key
        run: touch .ssh/env_key && echo ${{ secrets.KEY}} > .ssh/env_key

      - name: Copy a run script
        run: rsync deployments/run.sh ${{ secrets.HOST}}:${{ secrets.ROOT_PATH}}${{ vars.RUN_SCRIPT_PATH}}
        
      - name: Run an updated service
        run: ssh ${{ secrets.HOST}} 'source .profile; ${{ vars.RUN_SCRIPT_PATH}}'
  