name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build an image
        run: make build

      - name: Push an image
        run: docker push andreyad/helsinki-guide

      - name: Create an SSH key
        run: touch .ssh/env_key && ${{ environment.KEY}} > .ssh/env_key

      - name: Copy a run script
        run: rsync deployments/run.sh ${{ environment.HOST}}:${{ environment.SCRIPT_PATH}}
        
      - name: Run an updated service
        run: ssh ${{ environment.HOST}} 'source .profile; ${{ environment.SCRIPT_PATH}}'
  