name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      DB_URL: ${{ secrets.DatabaseURL}}
      BOT_TOKEN: ${{ secrets.BotAPIToken}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build an image
        run: make build

      - name: Push an image
        run: docker push andreyad/helsinki-guide

      - name: Copy and run a script
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.HOST}}
          user: ${{ secrets.USER}}
          pass: ${{ secrets.PASSWORD}}
          scp: ./deployments${{ vars.SCRIPT_PATH}} => ${{ secrets.ROOT_PATH}}
          last_ssh: source ${{ secrets.ROOT_PATH}}${{ vars.SCRIPT_PATH}} "$DB_URL" "$BOT_TOKEN"
  