name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      RUN_COMMAND: ${{ secrets.ROOT_PATH}}${{ vars.SCRIPT_PATH}} ${{ secrets.DATABASE_URL}} ${{ secrets.BOT_TOKEN}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build an image
        run: make build

      - name: Push an image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/helsinki-guide

      - name: Add an SSH key
        run: touch ~/.ssh/env_key && echo '${{ secrets.KEY}}' > ~/.ssh/env_key && chmod 600 ~/.ssh/env_key
      
      - name: Copy a startup script
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/env_key ./deployments${{ vars.SCRIPT_PATH}} ${{ secrets.USER}}@${{ secrets.HOST}}:${{ secrets.ROOT_PATH}}

      - name: Run the service
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/env_key ${{ secrets.USER}}@${{ secrets.HOST}} "source $RUN_COMMAND"